seed = 0
batch_size = 256
patience = 16
n_epochs = inf
# n_epochs = 1

context_size = 96
# context_size = 8

[data]
seed = 0
cache = true
path = ":data/churn"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "__null__"

[model]
num_embeddings = "__null__"
# d_main = 315
d_main = 128

context_dropout = 0.4072526399472316
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.4464799742742301
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[optimizer]
type = "AdamW"
lr = 0.00012852202346146056
weight_decay = 0.0
